USE [master]
GO

/****** Object:  Database [Iskhakov_Glazki]    Script Date: 25.10.2023 13:14:33 ******/
CREATE DATABASE [Iskhakov_Glazki]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Iskhakov_Glazki', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Iskhakov_Glazki.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Iskhakov_Glazki_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Iskhakov_Glazki_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Iskhakov_Glazki].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Iskhakov_Glazki] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Iskhakov_Glazki] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Iskhakov_Glazki] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Iskhakov_Glazki] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Iskhakov_Glazki] SET ARITHABORT OFF 
GO

ALTER DATABASE [Iskhakov_Glazki] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Iskhakov_Glazki] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Iskhakov_Glazki] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Iskhakov_Glazki] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Iskhakov_Glazki] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Iskhakov_Glazki] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Iskhakov_Glazki] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Iskhakov_Glazki] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Iskhakov_Glazki] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Iskhakov_Glazki] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Iskhakov_Glazki] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Iskhakov_Glazki] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Iskhakov_Glazki] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Iskhakov_Glazki] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Iskhakov_Glazki] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Iskhakov_Glazki] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Iskhakov_Glazki] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Iskhakov_Glazki] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Iskhakov_Glazki] SET  MULTI_USER 
GO

ALTER DATABASE [Iskhakov_Glazki] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Iskhakov_Glazki] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Iskhakov_Glazki] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Iskhakov_Glazki] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Iskhakov_Glazki] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Iskhakov_Glazki] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Iskhakov_Glazki] SET  READ_WRITE 
GO


